-- FlowWeft Workflow SLA owns V038; legacy compatibility migrations and approval tables remain untouched.
CREATE TABLE fw_wf_sla_schedule (
    id varchar(64) NOT NULL,
    tenant_id varchar(512) NOT NULL,
    schedule_id varchar(512) NOT NULL,
    idempotency_key varchar(512) NOT NULL,
    idempotency_binding_digest varchar(64) NOT NULL,
    policy_id varchar(128) NOT NULL,
    policy_version varchar(1024) NOT NULL,
    source_policy_digest varchar(64) NOT NULL,
    policy_digest varchar(64) NOT NULL,
    definition_id varchar(512) NOT NULL,
    definition_key varchar(256) NOT NULL,
    definition_version varchar(128) NOT NULL,
    definition_digest varchar(64) NOT NULL,
    node_id varchar(128) NOT NULL,
    calendar_profile_id varchar(128) NOT NULL,
    calendar_profile_version varchar(1024) NOT NULL,
    calendar_profile_digest varchar(64) NOT NULL,
    calendar_profile_binding_digest varchar(64) NOT NULL,
    calendar_provider_id varchar(128) NOT NULL,
    calendar_id varchar(128) NOT NULL,
    calendar_version varchar(1024) NOT NULL,
    calendar_digest varchar(64) NOT NULL,
    calendar_runtime_revision varchar(1024) NOT NULL,
    calendar_call_window bigint NOT NULL,
    calendar_maximum_input integer NOT NULL,
    calendar_maximum_output integer NOT NULL,
    calendar_binding_digest varchar(64) NOT NULL,
    action_profile_id varchar(128) NOT NULL,
    action_profile_version varchar(1024) NOT NULL,
    action_profile_digest varchar(64) NOT NULL,
    action_provider_id varchar(128) NOT NULL,
    action_provider_revision varchar(1024) NOT NULL,
    action_call_window bigint NOT NULL,
    action_maximum_input integer NOT NULL,
    action_maximum_output integer NOT NULL,
    action_maximum_attempts integer NOT NULL,
    action_retry_delay bigint NOT NULL,
    action_binding_digest varchar(64) NOT NULL,
    instance_id varchar(512) NOT NULL,
    work_item_id varchar(512) NOT NULL,
    task_status varchar(64) NOT NULL,
    task_revision bigint NOT NULL,
    task_digest varchar(64) NOT NULL,
    task_activated_time bigint NOT NULL,
    task_observed_time bigint NOT NULL,
    subject_type varchar(64) NOT NULL,
    subject_id varchar(512) NOT NULL,
    subject_revision varchar(256) NOT NULL,
    subject_digest varchar(64) NOT NULL,
    task_snapshot_digest varchar(64) NOT NULL,
    schedule_status varchar(64) NOT NULL,
    schedule_version bigint NOT NULL,
    prepare_authorization_digest varchar(64) NOT NULL,
    commit_authorization_digest varchar(64) NOT NULL,
    schedule_content_digest varchar(64) NOT NULL,
    last_operation_code varchar(64) NOT NULL,
    last_operation_digest varchar(64) NOT NULL,
    last_operation_base_version bigint NOT NULL,
    created_time bigint NOT NULL,
    updated_time bigint NOT NULL,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, schedule_id),
    UNIQUE (tenant_id, idempotency_key),
    UNIQUE (tenant_id, instance_id, work_item_id),
    CHECK (schedule_version >= 0),
    CHECK (task_revision >= 0),
    CHECK (updated_time >= created_time)
);
CREATE INDEX idx_fw_wf_sla_schedule_status
    ON fw_wf_sla_schedule(tenant_id, schedule_status, updated_time);
CREATE INDEX idx_fw_wf_sla_schedule_task
    ON fw_wf_sla_schedule(tenant_id, instance_id, work_item_id);

CREATE TABLE fw_wf_sla_milestone (
    id varchar(64) NOT NULL,
    tenant_id varchar(512) NOT NULL,
    schedule_id varchar(512) NOT NULL,
    milestone_ordinal integer NOT NULL,
    milestone_kind varchar(64) NOT NULL,
    action_kind varchar(64) NOT NULL,
    working_duration bigint NOT NULL,
    scheduled_for bigint NOT NULL,
    calendar_evaluation_digest varchar(64) NOT NULL,
    status_code varchar(64) NOT NULL,
    attempt_count integer NOT NULL,
    fence_sequence bigint NOT NULL,
    lease_id varchar(512),
    worker_id varchar(512),
    lease_fencing_token bigint,
    lease_acquired_time bigint,
    lease_expires_time bigint,
    next_attempt_time bigint,
    action_request_digest varchar(64),
    authorization_evidence_digest varchar(64),
    receipt_provider_id varchar(128),
    receipt_provider_revision varchar(1024),
    receipt_action_profile_digest varchar(64),
    receipt_request_digest varchar(64),
    receipt_outcome varchar(64),
    receipt_result_evidence_digest varchar(64),
    receipt_failure_code varchar(128),
    receipt_requested_time bigint,
    receipt_deadline_time bigint,
    receipt_completed_time bigint,
    receipt_expires_time bigint,
    receipt_digest varchar(64),
    outcome_evidence_digest varchar(64),
    milestone_content_digest varchar(64) NOT NULL,
    created_time bigint NOT NULL,
    updated_time bigint NOT NULL,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, schedule_id, milestone_kind),
    FOREIGN KEY (tenant_id, schedule_id)
        REFERENCES fw_wf_sla_schedule(tenant_id, schedule_id),
    CHECK (milestone_ordinal >= 0),
    CHECK (working_duration > 0),
    CHECK (attempt_count >= 0),
    CHECK (fence_sequence >= 0),
    CHECK ((lease_id IS NULL AND worker_id IS NULL AND lease_fencing_token IS NULL AND
            lease_acquired_time IS NULL AND lease_expires_time IS NULL) OR
           (lease_id IS NOT NULL AND worker_id IS NOT NULL AND lease_fencing_token IS NOT NULL AND
            lease_acquired_time IS NOT NULL AND lease_expires_time IS NOT NULL))
);
CREATE INDEX idx_fw_wf_sla_milestone_due
    ON fw_wf_sla_milestone(tenant_id, status_code, next_attempt_time, scheduled_for);
CREATE INDEX idx_fw_wf_sla_milestone_lease
    ON fw_wf_sla_milestone(tenant_id, status_code, lease_expires_time);
