-- FlowWeft cycle-guard schema contract. It is not auto-run; the owning deployment assigns a migration version.
CREATE TABLE fw_wf_cycle_guard_total (
    id varbinary(64) NOT NULL,
    tenant_id varbinary(512) NOT NULL,
    aggregate_digest varchar(64) NOT NULL,
    instance_id varbinary(512) NOT NULL,
    definition_id varbinary(512) NOT NULL,
    definition_key varchar(256) NOT NULL,
    definition_version varchar(128) NOT NULL,
    definition_digest varchar(64) NOT NULL,
    operation_code varchar(128) NOT NULL,
    subject_type varchar(64) NOT NULL,
    subject_id varbinary(512) NOT NULL,
    policy_id varchar(128) NOT NULL,
    policy_version varchar(128) NOT NULL,
    policy_digest varchar(64) NOT NULL,
    policy_binding_digest varchar(64) NOT NULL,
    policy_authority_revision varchar(256) NOT NULL,
    maximum_per_cycle integer NOT NULL,
    maximum_per_instance integer NOT NULL,
    operation_count integer NOT NULL,
    aggregate_revision bigint NOT NULL,
    created_time bigint NOT NULL,
    updated_time bigint NOT NULL,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, aggregate_digest),
    CHECK (maximum_per_cycle > 0),
    CHECK (maximum_per_instance >= maximum_per_cycle),
    CHECK (operation_count > 0 AND operation_count <= maximum_per_instance),
    CHECK (aggregate_revision > 0),
    CHECK (updated_time >= created_time)
);
CREATE INDEX idx_fw_wf_cycle_guard_total_instance
    ON fw_wf_cycle_guard_total(tenant_id, instance_id, operation_code, updated_time);

CREATE TABLE fw_wf_cycle_guard_cycle (
    id varbinary(64) NOT NULL,
    tenant_id varbinary(512) NOT NULL,
    scope_digest varchar(64) NOT NULL,
    aggregate_digest varchar(64) NOT NULL,
    instance_id varbinary(512) NOT NULL,
    definition_id varbinary(512) NOT NULL,
    definition_key varchar(256) NOT NULL,
    definition_version varchar(128) NOT NULL,
    definition_digest varchar(64) NOT NULL,
    node_id varchar(512) NOT NULL,
    operation_code varchar(128) NOT NULL,
    cycle_number bigint NOT NULL,
    subject_type varchar(64) NOT NULL,
    subject_id varbinary(512) NOT NULL,
    subject_revision varchar(256) NOT NULL,
    subject_digest varchar(64) NOT NULL,
    policy_id varchar(128) NOT NULL,
    policy_version varchar(128) NOT NULL,
    policy_digest varchar(64) NOT NULL,
    policy_content_digest varchar(64) NOT NULL,
    policy_authority_revision varchar(256) NOT NULL,
    maximum_per_cycle integer NOT NULL,
    maximum_per_instance integer NOT NULL,
    per_cycle_count integer NOT NULL,
    last_instance_operation_count integer NOT NULL,
    guard_revision bigint NOT NULL,
    last_idempotency_key varbinary(128) NOT NULL,
    last_request_digest varchar(64) NOT NULL,
    last_authorization_decision_digest varchar(64) NOT NULL,
    last_record_digest varchar(64) NOT NULL,
    created_time bigint NOT NULL,
    updated_time bigint NOT NULL,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, scope_digest),
    CHECK (cycle_number >= 0),
    CHECK (maximum_per_cycle > 0),
    CHECK (maximum_per_instance >= maximum_per_cycle),
    CHECK (per_cycle_count > 0 AND per_cycle_count <= maximum_per_cycle),
    CHECK (last_instance_operation_count >= per_cycle_count),
    CHECK (last_instance_operation_count <= maximum_per_instance),
    CHECK (guard_revision > 0),
    CHECK (updated_time >= created_time)
);
CREATE INDEX idx_fw_wf_cycle_guard_cycle_instance
    ON fw_wf_cycle_guard_cycle(tenant_id, instance_id, operation_code, cycle_number);

CREATE TABLE fw_wf_cycle_guard_receipt (
    id varbinary(64) NOT NULL,
    tenant_id varbinary(512) NOT NULL,
    idempotency_key varbinary(128) NOT NULL,
    scope_digest varchar(64) NOT NULL,
    aggregate_digest varchar(64) NOT NULL,
    policy_id varchar(128) NOT NULL,
    policy_version varchar(128) NOT NULL,
    policy_digest varchar(64) NOT NULL,
    policy_content_digest varchar(64) NOT NULL,
    policy_authority_revision varchar(256) NOT NULL,
    maximum_per_cycle integer NOT NULL,
    maximum_per_instance integer NOT NULL,
    per_cycle_count integer NOT NULL,
    instance_operation_count integer NOT NULL,
    guard_revision bigint NOT NULL,
    command_request_digest varchar(64) NOT NULL,
    consume_request_digest varchar(64) NOT NULL,
    authorization_decision_digest varchar(64) NOT NULL,
    record_digest varchar(64) NOT NULL,
    created_time bigint NOT NULL,
    updated_time bigint NOT NULL,
    PRIMARY KEY (tenant_id, id),
    UNIQUE (tenant_id, idempotency_key),
    CHECK (maximum_per_cycle > 0),
    CHECK (maximum_per_instance >= maximum_per_cycle),
    CHECK (per_cycle_count > 0 AND per_cycle_count <= maximum_per_cycle),
    CHECK (instance_operation_count >= per_cycle_count),
    CHECK (instance_operation_count <= maximum_per_instance),
    CHECK (guard_revision > 0),
    CHECK (updated_time >= created_time)
);
CREATE INDEX idx_fw_wf_cycle_guard_receipt_scope
    ON fw_wf_cycle_guard_receipt(tenant_id, scope_digest, guard_revision);
