FROM redis:8.6.4@sha256:aa6acc8e590894b180ebc89fdb701e9dd64fdd33cde018e4b6bf170d4fc3bbe9 AS redis

FROM node:24.9.0-trixie-slim@sha256:7597ef941ddc27f91d22f7a31d9d16ea77db8bb1a6e6b3f2f6dd4a402420a7b0

ENV CI=true \
    NEXT_TELEMETRY_DISABLED=1

WORKDIR /workspace

COPY --from=redis /usr/local/bin/redis-server /usr/local/bin/redis-server
COPY --from=redis /usr/local/bin/redis-cli /usr/local/bin/redis-cli

RUN node --version \
    && npm --version \
    && redis-server --version \
    && redis-cli --version
