# syntax=docker/dockerfile:1.7

FROM node:24.9.0-bookworm-slim@sha256:3e69116c924bfcba6c6979aff60d966c37aef56d488ce091c69d442ebec9f103

ENV CI=true \
    NEXT_TELEMETRY_DISABLED=1

WORKDIR /workspace

RUN node --version && npm --version
