package ai.icen.fw.application.delivery

/**
 * Fixed public classification of a persisted delivery failure diagnostic.
 *
 * This category is the only diagnostic-derived value that may cross the
 * public synchronization status boundary. Raw diagnostics are generated by
 * the framework or a connector and may carry host policy, storage, or
 * database details, so the text itself must never be echoed back; any
 * diagnostic that does not match a known framework phrase collapses to
 * [UNKNOWN] instead of leaking through.
 *
 * Categories and their real failure sources:
 * - [TARGET_NOT_FOUND]: the delivery target row is absent or was removed in
 *   the event tenant.
 * - [DOCUMENT_UNAVAILABLE]: the document is missing, removed, in an
 *   undeliverable lifecycle state, or lost its active version or file object.
 * - [FENCE_INVALID]: the delivery target is missing its dispatch fence.
 * - [CONNECTOR_FAILURE]: connector resolution, configuration, or invocation
 *   failed, or the connector returned an unusable result.
 * - [STORAGE_FAILURE]: the storage adapter could not prepare the source
 *   access URL handed to the connector.
 * - [PERSISTENCE_FAILURE]: a database failure escaped the worker and was
 *   recorded through the Outbox wrapper diagnostic.
 * - [UNKNOWN]: every other persisted diagnostic, including vendor supplied
 *   connector messages and generic retry exhaustion fallbacks.
 */
enum class DocumentDeliveryErrorCategory {
    TARGET_NOT_FOUND,
    DOCUMENT_UNAVAILABLE,
    FENCE_INVALID,
    CONNECTOR_FAILURE,
    STORAGE_FAILURE,
    PERSISTENCE_FAILURE,
    UNKNOWN,
;

    companion object {
        /**
         * Classifies one persisted internal diagnostic. Null or blank input
         * means no diagnostic was recorded and yields null; unrecognized text
         * yields [UNKNOWN]. The function is pure, deterministic, and matches
         * only fixed framework phrases or the Outbox wrapper's exception
         * class segment, never user or vendor controlled content.
         */
        @JvmStatic
        fun classify(diagnostic: String?): DocumentDeliveryErrorCategory? {
            val text = diagnostic?.trim()?.takeIf { it.isNotEmpty() } ?: return null
            EXACT_CATEGORIES[text]?.let { return it }
            return when {
                text.startsWith(DOCUMENT_LIFECYCLE_PREFIX) -> DOCUMENT_UNAVAILABLE
                text.startsWith(CONNECTOR_NOT_CONFIGURED_PREFIX) -> CONNECTOR_FAILURE
                text.startsWith(CONNECTOR_INVALID_RESULT_PREFIX) -> CONNECTOR_FAILURE
                text.startsWith(OUTBOX_HANDLER_FAILED_PREFIX) ->
                    classifyOutboxException(text.substringAfter(OUTBOX_HANDLER_FAILED_PREFIX))
                text.startsWith(OUTBOX_SELECTION_FAILED_PREFIX) ->
                    classifyOutboxException(text.substringAfter(OUTBOX_SELECTION_FAILED_PREFIX))
                else -> UNKNOWN
            }
        }

        /** The Outbox wrapper names the escaped exception class before any message. */
        private fun classifyOutboxException(wrapperRemainder: String): DocumentDeliveryErrorCategory {
            val exceptionClass = wrapperRemainder.substringBefore(':').trim().lowercase()
            return if (PERSISTENCE_CLASS_TOKENS.any(exceptionClass::contains)) {
                PERSISTENCE_FAILURE
            } else {
                UNKNOWN
            }
        }

        private val EXACT_CATEGORIES: Map<String, DocumentDeliveryErrorCategory> = mapOf(
            "Delivery target was not found in the event tenant." to TARGET_NOT_FOUND,
            "Delivery target was removed before synchronization completed." to TARGET_NOT_FOUND,
            "Document was not found in the event tenant." to DOCUMENT_UNAVAILABLE,
            "Document was removed before synchronization completed." to DOCUMENT_UNAVAILABLE,
            "Document has no active version." to DOCUMENT_UNAVAILABLE,
            "Active document version references a missing file object." to DOCUMENT_UNAVAILABLE,
            "Delivery target is missing its dispatch fence." to FENCE_INVALID,
            "Delivery connector resolution could not complete." to CONNECTOR_FAILURE,
            "Connector invocation could not complete." to CONNECTOR_FAILURE,
            "Storage source access could not be prepared." to STORAGE_FAILURE,
        )
        private const val DOCUMENT_LIFECYCLE_PREFIX = "Document is not available for delivery from lifecycle state"
        private const val CONNECTOR_NOT_CONFIGURED_PREFIX = "Delivery connector '"
        private const val CONNECTOR_INVALID_RESULT_PREFIX = "Connector reported success with an invalid external identifier"
        private const val OUTBOX_HANDLER_FAILED_PREFIX = "Outbox handler failed: "
        private const val OUTBOX_SELECTION_FAILED_PREFIX = "Outbox handler selection failed: "
        private val PERSISTENCE_CLASS_TOKENS = listOf("sql", "jdbc", "dataaccess", "persistence")
    }
}
